### ISSUE TITLE
token managment

### ISSUE THREAD

**Issue by nikto1** [jech/galene#186]
Took a look at the token management and the tokens in the `tokens.jsonl` file are never deleted. With time this would cause a huge file if you work with tokens instead of username+pass to login.

Wouldn't it be much better to:
1) make a `tokens.jsonl` file for each group. Actually an admin from one group can see all tokens while he should just see the tokens from his own group.
2) delete the token completely instead of just modifying the expiry date of the token. As for now you have to go through a list of 20, 50, ecc. tokens in order to modify the expiry time.
3) using the token revoke function by `/revoke user` instead of `/revoke link`, much easier to write + a username is always easier to remember while a link is impossible to remember. 
4) supposing 1 is already implemented,  delete the jsonl file an x amount of time/ after a meeting is finished or the .jsonl file gets deleted together with the group.json file.

**Comment by jech** [comment]
> Took a look at the token management and the tokens in the tokens.jsonl file are never deleted.

They are deleted a week after they expire: https://github.com/jech/galene/blob/master/token/stateful.go#L372

(The reason they are not deleted earlier is that it is possible to extend a token after it has expired using `/reinvite`.)

> make a tokens.jsonl file for each group

That was my first design and I even started coding it, but it turned out to be too complicated, so I settled for the current design.  We can always revisit this if there are clear advantages to the more complex approach.

> Actually an admin from one group can see all tokens while he should just see the tokens from his own group.

It's not supposed to do that: https://github.com/jech/galene/blob/master/token/stateful.go#L329.  Have you actually tried it, or are you just guessing?

> using the token revoke function by /revoke user instead of /revoke link

Not a bad idea, but we usually use tokens with no username, so we haven't found the need for this feature.  Additionally, you'd need to define what to do when there are multiple tokens for the same user. I'd be open to accepting a patch that adds a new command that does what you suggest.

> supposing 1 is already implemented, delete the jsonl file an x amount of time/ after a meeting is finished

We already delete the file when all tokens have expired, see https://github.com/jech/galene/blob/master/token/stateful.go#L264.

**Comment by jech** [comment]
>> They are deleted a week after they expire: https://github.com/jech/galene/blob/master/token/stateful.go#L372

> Maybe would be better to delete tokens as soon as there is no one in the meeting

Why would it be better?

> Would be good if it's possible to delete tokens by username too

As I've said before, I think it's a good idea.

**Comment by jech** [comment]
> because the file gets big if you have quite some meetings running each day

How large is your tokens file?  I could easily make the delay configurable, but I'd need some concrete data to convince me it's worth it.
