### ISSUE TITLE
Feature request (Accessibility): Optional Speech-to-Text (STT) integration

### ISSUE THREAD

**Issue by TechnologyClassroom** [jech/galene#202]
Adding speech to text to Galène would greatly help people that have trouble hearing. The whisper and vosk models can be self-hosted and run on low resource machines which could potentially pair well with Galène. [livestream.sh](https://github.com/ggerganov/whisper.cpp/blob/master/examples/livestream.sh) is an example of nearly real-time transcription with whisper using only CPU.

I recognize that this could be a difficult item, but I do want to put it out there as it could have a great impact.

**Comment by jech** [comment]
I'm open to the idea, but I'd need to speak with the people who actually need the feature.  In particular, I'd need to understand why they don't use a system-wide speech-to-text system.

I have spoken to visually impaired users of Galene, and they tell me that they use a system-wide screenreader, and therefore don't need TTS support in Galene itself, they just need the Galene UI to be accessible (which is apparently the case). Before implementing the feature you request, I need to understand whether hearing impaired users use a system-wide speech-to-text system, and, if they don't, why.

**Comment by jech** [comment]
Ah-ha, you're thinking of server-side TTS.  Yes, that makes more sense.

I think this could by done by writing a separate client that connects to the Galene server and does TTS then publishes the resulting text in the chat.  This could be run on any computer, which would avoid putting CPU intensive stuff on the Galene server.

Please don't hold your breath.

**Comment by jech** [comment]
I've got a very early prototype.  On my laptop, it takes 290% CPU to transcribe a single stream in real time, and on the order of 500MB of RAM.  That's using 2s segments and the `ggml-base.en.bin` model.

**Comment by jech** [comment]
I've done some more experimenting.  The smallest model available "tiny_q5.1", runs in real-time on my laptop, but the quality is not useful (it mostly produces hallucinations).  The base.en model almost runs in real-time (it drops runs of packets), and it occasionally produces useful data.

Unfortunately, whisper.cpp is not able to produce a transcript incrementally, so I'm chopping the audio into two-second segments which I then pass to whisper.  Better results could probably be achieved by using a smarter segmentation strategy, or by using a TTS engine that is able to perform incremental transcription.  See also https://github.com/ggerganov/whisper.cpp/issues/1976.

In order to continue working on this, I would need ssh access to a machine much more powerful than the ones I currently have access to.

**Comment by jech** [comment]
Increasing the segment size to 5s improves the results quite a bit.  A better segmentation strategy is needed.

**Comment by jech** [comment]
After some more tweaking, it's sort of usable.  Please see https://github.com/jech/galene-stt
