### ISSUE TITLE
the android sdk is not open?

### ISSUE THREAD

**Issue by czk630597526** [jech/galene#224]
the android sdk is not open?

**Comment by jech** [comment]
There's no Android SDK.  There's an Android application the source code of which is not publicly available.

I don't feel comfortable opensourcing the Android app, since I'm only just learning Android and am not very proud of my code.  However, I could easily separate out the protocol code and make it available under a liberal licence.  Please tell me what you're trying to do, and I'll see how I can help you.

**Comment by czk630597526** [comment]
> There's no Android SDK. There's an Android application the source code of which is not publicly available.
> 
> I don't feel comfortable opensourcing the Android app, since I'm only just learning Android and am not very proud of my code. However, I could easily separate out the protocol code and make it available under a liberal licence. Please tell me what you're trying to do, and I'll see how I can help you.

thanks for replying
