### ISSUE TITLE
Uniqueness of usernames

### ISSUE THREAD

**Issue by oddfellow** [jech/galene#36]
In a group with `"presenter": [{}]` I can login with the same username multiple times (from different browsers). This makes it impossible for an op to distinguish them for a user-targeting command like `/kick` or `/mute`.

Could it be possible to enforce the uniqueness of usernames in such groups? The user could be given a message like for example "This username is already taken, please chose another one".

**Comment by jech** [comment]
This is actually a feature: a user should be able to login multiple times.  For example, a fairly common configuration is to film oneself using a smartphone while using a laptop for screen sharing.

The underlying protocol actually handles duplicate usernames just fine: the users are identified by their user-id in the protocol, which is globally unique.  I'm looking for ideas about how to fix the UI without disabling the ability to log in multiple times with the same username.

**Comment by MisterDA** [comment]
> the users are identified by their user-id in the protocol, which is
> globally unique. I'm looking for ideas about how to fix the UI without
> disabling the ability to log in multiple times with the same username.

Append a prefix of the user-id to the username in case of collision of
the usernames. You could use the shortest differing prefix of the
user-id to minimise the noise, or always use a minimum length. This is
how Discord does it, so I think people are accustomed to this trick.

    username	id					displayed
    juliusz	6a12e711b17d927d4bd1bec7ba530263	juliusz#6a12
    juliusz	94c11c868286cfe2895c09414d7291d1	juliusz#94c1

some ideas for the UI would include using base 10 instead of base 16,
displaying the tag in a lighter tone, autocompleting the user name.

or you could allow a maximum of N colliding usernames and use around
log(N) characters to differentiate them just like above. I suggest
2 <= N <= 4, and strongly advise against anything more than 42.

-- Antonin

**Comment by jech** [comment]
> Append a prefix of the user-id to the username in case of collision of
> the usernames.

No.

> autocompleting the user name.

Yes.

**Comment by oddfellow** [comment]
Never thought of this use-case :-)

As for ideas:
- give OPs a command that lists the unique user-id along the username (for example `/users` or `/list users)`
- make the user-targeting commands also accept user-ids
- display the user-ids (for OPs only?) as text near the username beneath the media streams or a `/toggle username` which toggles between displaying username and user-id under the media stream
- ...

**Comment by jech** [comment]
> * make the user-targeting commands also accept user-ids

They already do.
